/*
 Archivo SQL para genera las tablas y añadir los primeros registros ademas de el catalogo necesario

 */
CREATE TABLE IF NOT EXISTS TBLSOBREVIVIENTES
(
    id_sobreviviente VARCHAR(60) GENERATED BY DEFAULT AS IDENTITY,
    nombre_sobreviviente VARCHAR(50),  edad VARCHAR(50),  genero VARCHAR(50),  latitud VARCHAR(50),
    longitud VARCHAR,  es_infectado BOOLEAN

    );

CREATE TABLE IF NOT EXISTS TBLINVENTARIO
(
    id_inventario VARCHAR(60) GENERATED BY DEFAULT AS IDENTITY,  id_sobreviviente INT,
    cantidad INT,id_objeto INT
);

CREATE TABLE IF NOT EXISTS catObjetos
(
    id_objeto INT,  descripcion VARCHAR(50),  puntos INT
    );

CREATE TABLE IF NOT EXISTS TBLREPORTESINFECTADOS
(
    id_reporte VARCHAR(60) GENERATED BY DEFAULT AS IDENTITY,  id_sobreviviente_infectado INT,
    id_sobreviviente_informante INT
);

truncate table catObjetos;
truncate table TBLINVENTARIO;
truncate table TBLSOBREVIVIENTES;

INSERT INTO catObjetos (id_objeto, descripcion,puntos) VALUES
                                                           (1,'Agua',4),
                                                           (2,'Comida',3),
                                                           (3,'Medicamentos',2),
                                                           (4,'Municiones',1);

INSERT INTO TBLINVENTARIO (id_sobreviviente, cantidad,id_objeto) VALUES
                                                           (1,1,4),
                                                           (1,2,3),
                                                           (1,3,2),
                                                           (1,4,1);

INSERT INTO TBLSOBREVIVIENTES (nombre_sobreviviente, edad,genero,latitud,longitud,es_infectado) VALUES
                                                                  ('Antonio','24','Hombre','25.6507','-100.312',0);